# Generated by Django 4.2.4 on 2023-08-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("skill_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "skill_name",
                    models.CharField(max_length=255, verbose_name="Nom de compétence"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillTest",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skill",
                        verbose_name="Compétence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField(verbose_name="question")),
                (
                    "correct_answer",
                    models.CharField(max_length=255, verbose_name="Réponse correcte"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skilltest",
                        verbose_name="Test",
                    ),
                ),
            ],
        ),
    ]
