# Generated by Django 4.2.4 on 2023-08-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant du paiement",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Date de paiement")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Pending", "Pending"),
                            ("Failed", "Failed"),
                        ],
                        max_length=255,
                        verbose_name="Statut de paiement",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companysubscription",
                        verbose_name="Abonnement",
                    ),
                ),
            ],
        ),
    ]
