# Generated by Django 4.2.4 on 2023-08-29 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("param", "0001_initial"),
        ("skills", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nom complet"),
                ),
                (
                    "date_of_birth",
                    models.DateField(null=True, verbose_name="Date de naissance"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CandidateCV",
            fields=[
                ("cv_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.TextField(null=True, verbose_name="Adresse")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Numéro de téléphone"
                    ),
                ),
                ("projects", models.TextField(null=True, verbose_name="Projets")),
                ("languages", models.TextField(null=True, verbose_name="Langues")),
                ("summary", models.TextField(null=True, verbose_name="Résumé")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condidate.candidate",
                        verbose_name="Candidat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestSubmission",
            fields=[
                ("submission_id", models.AutoField(primary_key=True, serialize=False)),
                ("submission_timestamp", models.DateTimeField(auto_now_add=True)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ranking", models.IntegerField(verbose_name="Classement")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condidate.candidate",
                        verbose_name="Candidat",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skilltest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CVExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=255, verbose_name="Poste")),
                (
                    "company",
                    models.CharField(max_length=255, verbose_name="Entreprise"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(null=True, verbose_name="Date de fin")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condidate.candidatecv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CVEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=255, verbose_name="Institution"),
                ),
                ("degree", models.CharField(max_length=255, verbose_name="Diplôme")),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(null=True, verbose_name="Date de fin")),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condidate.candidatecv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condidate.candidate",
                        verbose_name="Candidat",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skill",
                        verbose_name="Compétence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence du candidat",
            },
        ),
        migrations.CreateModel(
            name="CandidateRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ranking", models.IntegerField(verbose_name="Classement")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condidate.candidate",
                        verbose_name="Candidat",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skill",
                        verbose_name="Compétence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateApplication",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "application_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de candidature"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Reviewed", "Reviewed"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=255,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condidate.candidate",
                        verbose_name="Candidat",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.job",
                        verbose_name="Emploi",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="candidateskill",
            constraint=models.UniqueConstraint(
                fields=("candidate", "skill"), name="unique_candidate_skill_"
            ),
        ),
    ]
